### ISSUE TITLE
Shorter and more einops-y?

### ISSUE THREAD

**Issue by arogozhnikov** [lucidrains/conformer#4]
@lucidrains I enjoy your super-readable implementations, and I think we can make them ever simpler. 
Here are a couple of suggestions:

Einops provides layers (`einops.layers.torch`) which could make it more verbose:
```python
# was 
Transpose((1, 2))
<convolutional part>
Transpose((1, 2))

# now
Rearrange('b token c -> b c token'),
<convolutional part>
Rearrange('b c token -> b token c'),
```

This part of code looks a bit over-engineered:

```python
q, k, v = (self.to_q(x), *self.to_kv(context).chunk(2, dim = -1))
q, k, v = map(lambda t: rearrange(t, 'b n (h d) -> b h n d', h = h), (q, k, v))
```

How about using a new layer from einops:
```python
self.to_qkv = WeightedEinsum('b n c -> qkv b h n d', qkv=3, h=heads, d=inner_dim//heads)
# then in forward
q, k, v = self.to_qkv(x)
```
This change will also remove need to store/pass heads info and will remove 2-4 more lines.

Sounds like a great place to use einsum? Still need add one None-axis afterwards, but I'd give it a go to make it obvious
```
mask = mask[:, None, :, None] * context_mask[:, None, None, :]
```

PS. Actually enjoyed reading the code. Like read a paper in several minutes :)

**Comment by lucidrains** [comment]
@arogozhnikov Hello Alex! Thanks for dropping by :) I tried everything and it works like a charm. I am going to hold back from using `WeightedEinsum` until it leaves the experimental phase, but otherwise I added all your other feedback, and will be certain to use `WeightedEinsum` for my other non-published projects in the future

Einops is so so awesome! please allow me to buy you a beer in San Francisco (I live here too) once Covid is over :)

**Comment by arogozhnikov** [comment]
@lucidrains awesome! So glad people enjoying einops. 

Ok, one more motivation to stabilize WeightedEinsum :)

**Comment by lucidrains** [comment]
yea, i think you're brilliant! lolll
